# Site settings
# Site settings
title: Kunal Bhardwaj | Data Scientist & AI Product Strategist
description: Portfolio for [Kunal Bhardwaj], a product-focused data scientist specializing in taking Generative AI and ML models from concept to market.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://AI-alchemist-kunal.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kunal Bhardwaj
user_description: I'm a data scientist passionate about building and launching real-world AI products. With a strong foundation in Generative AI, machine learning, and product management, I specialize in translating complex data insights into business strategy and product-led growth.
user_title: Data Scientist | AI Product Strategist
email: kbms1412@gmail.com
github_username:  AI-alchemist-kunal
linkedin_username: kunalbhardwaj14
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
